// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQPgMwzb7A095GXjQ_04ehfCNxUinpRAs',
    appId: '1:1052785719487:web:888bc5144732b1059aee0a',
    messagingSenderId: '1052785719487',
    projectId: 'improvio-9f372',
    authDomain: 'improvio-9f372.firebaseapp.com',
    storageBucket: 'improvio-9f372.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0omRIvqGik8-vfbwWJg5LqOqx94Zd9I',
    appId: '1:1052785719487:android:0c61c25f2c105f689aee0a',
    messagingSenderId: '1052785719487',
    projectId: 'improvio-9f372',
    storageBucket: 'improvio-9f372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYH2gP6F0a5aJTzq72mSpEqly4Aeaie4',
    appId: '1:1052785719487:ios:2d7ec959e678b59c9aee0a',
    messagingSenderId: '1052785719487',
    projectId: 'improvio-9f372',
    storageBucket: 'improvio-9f372.appspot.com',
    iosClientId: '1052785719487-hbf73h27eqihrf032p1vqo245af6oo85.apps.googleusercontent.com',
    iosBundleId: 'improvio.app.improvio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoYH2gP6F0a5aJTzq72mSpEqly4Aeaie4',
    appId: '1:1052785719487:ios:2d7ec959e678b59c9aee0a',
    messagingSenderId: '1052785719487',
    projectId: 'improvio-9f372',
    storageBucket: 'improvio-9f372.appspot.com',
    iosClientId: '1052785719487-hbf73h27eqihrf032p1vqo245af6oo85.apps.googleusercontent.com',
    iosBundleId: 'improvio.app.improvio',
  );
}
